### ISSUE TITLE
error when running rosrun ar2landing_gazebo autonomous_landing.py~ 

### ISSUE THREAD

**Issue by nguyentranus1989** [krishnan793/ar2landing_neural#1]
Hi,
I tried to run rosrun ar2landing_gazebo autonomous_landing.py~  and i got this error:
Traceback (most recent call last):
  File "/home/nguyentran/catkin_ws/src/ar2landing_neural/ar2landing_gazebo/src/autonomous_landing.py~", line 101, in <module>
    search_pattern()
  File "/home/nguyentran/catkin_ws/src/ar2landing_neural/ar2landing_gazebo/src/autonomous_landing.py~", line 62, in search_pattern
    controller.SetCommand(0,0,0,1.5)
NameError: global name 'controller' is not defined

Would you please point out what i did wrong? Thank you so much

**Comment by krishnan793** [comment]
`rosrun ar2landing_gazebo autonomous_landing.py `
is the correct command not 
`rosrun ar2landing_gazebo autonomous_landing.py~`

**Comment by sreekanth1994** [comment]
I am also getting the same error like nguyentranus1989.... can you please  tell what we have to change... any command or any line in programme?
